import type { Metadata } from "next";
import { Plus_Jakarta_Sans, El_Messiri, Tajawal } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/contexts/CartContext";
import Header from "@/components/Header";
import { FavoritesProvider } from "@/contexts/FavoritesContext";
import { ProductsProvider } from "@/contexts/ProductsContext";

const plusJakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700", "800"],
  variable: "--font-jakarta",
  display: "swap",
});
const elMessiri = El_Messiri({
  subsets: ["arabic", "latin"],
  weight: ["400", "700"],
  variable: "--font-el-messiri",
  display: "swap",
});
const tajawal = Tajawal({
  subsets: ["arabic", "latin"],
  weight: ["400", "700"],
  variable: "--font-tajawal",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={`${plusJakarta.variable} ${elMessiri.variable} ${tajawal.variable} antialiased bg-[var(--color-background-light)] text-[var(--color-text-light)]`}>
        <ProductsProvider>
          <CartProvider>
            <FavoritesProvider>
              <Header />
              {children}
            </FavoritesProvider>
          </CartProvider>
        </ProductsProvider>
      </body>
    </html>
  );
}
